[build]
target = "riscv32imac-esp-espidf"
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "espflash flash --monitor --chip esp32c6"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c6"
ESP_IDF_VERSION = "v5.4.3"
